### PR TITLE
Fix RTAN violations

### PR DESCRIPTION
**Pull request by rollerozxa**
This game violates ContentDB's RTAN policy by having the game's mod be called `game`. This is too generic and makes it impossible for mods to correctly specify a dependency for this game.

Also fix deprecated use_texture_alpha, missing screenshot, game.conf title, hide node outline, force singlenode mapgen, use engine built-in blank.png instead of inv.png...

### CODE REVIEW

**Comment by ExeVirus** [comment]
Thanks for putting so much work into helping this game, I laughed at but appreciated the little "Congrats on complete X!" after completion. Thanks also for compressing the media, every little bit helps, right?

Anyways, I merged your really old hand = 0 distance commit, which now conflicts with this pull request, single line no biggie. Will merge after that is de-conflicted.

**Comment by rollerozxa** [comment]
"Congrats on complete X!", like the message that comes up when you finish a maze? I think that was in the game already, I didn't add that 😄 

Also I probably should have closed that other PR since it was already included in this one. I noticed I accidentally left a line that shouldn't be there in maze.lua when I was testing the ASCII maze rendering thing, so I'll remove that along with rebasing.

**Comment by ExeVirus** [comment]
Looks good to me, anything else you want to change before merge?

**Comment by rollerozxa** [comment]
Alright, rebased and removed the line I accidentally left in maze.lua, should now be good to be merged.

By the way if you didn't already see, I replaced the textures of the 3D maze screensaver mod I did a while back and put it up on ContentDB: https://content.minetest.net/packages/ROllerozxa/3dmaze/ :)

**Pull request merged**
